### ISSUE TITLE
Course view must be navigable

### ISSUE THREAD

**Issue by joonashak** [UniversityOfHelsinkiCS/prkl#196]
These buttons should indicate navigational intent more clearly (e.g., they should be tabs or smth). The different views should be frontend routes to enable navigation using browser back-fwd buttons.

<img width="870" alt="Screenshot 2021-02-19 at 9 48 05" src="https://user-images.githubusercontent.com/18666321/108474109-96c43000-7297-11eb-9200-6ba2b55361e5.png">

- [x] Routejen toteutus
- [x] /groups route ei aina toimi - fixattava
- [x] Navigointipalkki eri vieweihin
- [x] Testit

**Comment by Koppari** [comment]
To fix:
- Users who shouldn't be able to access subroutes can do it (nothing is rendered though)
