### ISSUE TITLE
GroupsView skaalautuvaksi eri screenwidtheille

### ISSUE THREAD

**Issue by tikibeni** [UniversityOfHelsinkiCS/prkl#207]
Tällä hetkellä GroupsView'n rivien painikkeet eivät tunnu skaalautuvan näytön leveyteen. Esimerkiksi punainen poistonappi saattaa jäädä kokonaan piiloon, mikäli selain on zoomattuna liikaa, tai näytön leveys ei ole tarpeeksi suuri. Sama ilmenee, jos kurssilla on monta kysymystä.

- [x] Kaikki elementit näkyväksi skaalatessa
- [x] Näytä tekstinpätkä kokonaan sitä hoveroidessa JOS se on truncatettu.

**Comment by Koppari** [comment]
14.3.2021:
Kaikki napit näkyvät nyt ikkunaa skaalatessa, mutta jos jokin tekstinpätkä on liian pitkä niin se truncatetaan. Tämän voisi korjata vaikka näyttämällä tekstinpätkän kokonaan sitä hoveroidessa JOS se on truncatettu.
