### ISSUE TITLE
docker-compose up frontin buildin automatisointi

### ISSUE THREAD

**Issue by marinellalaaksonen** [UniversityOfHelsinkiCS/prkl#21]

**Comment by joonashak** [comment]
Toimii tällä hetkellä niin, että ajaa erikseen `docker-compose up` ja toisessa shellissä frontin kansiossa `npm start`. Dockerin kautta hotloadaaminen ei vaikuta lainkaan triviaalilta fiksata, joten pitäisikö tämä katsoa tehdyksi ja keskittyä tärkeämpiin juttuihin? Miinuksena on käsittääkseni vain tuo ylimääräinen npm-komento ja pari riviä koodia frontissa API:n osoitteen togglaamiseksi.
