### ISSUE TITLE
Dokumentaatio megaissue

### ISSUE THREAD

**Issue by tikibeni** [UniversityOfHelsinkiCS/prkl#217]
Tällä hetkellä dokumentaatio ei ole ajan tasalla nykyisen toteutuksen muutoksien pohjalta. Seuraavaa toteutusta ajatellen olisi hyvä uudistaa ja luoda kattavampi dokumentaatio.
Lisää alle huomioita:
- [ ] Tietokantakaavio
- [ ] Vanhan tiedon uudistus / poisto (erityisesti algoritmia koskien)
- [ ] Kattavampi setup-ohje (esim. Dockerin osalta)
- [ ] Frontendin rakennekaavio (draw.io)
- [ ] Backendin rakennekaavio

**Comment by vuolen** [comment]
Split into smaller tasks
