### ISSUE TITLE
Opettajana pystyn poistamaan ilmoittautumisen kurssiltani

### ISSUE THREAD

**Issue by marinellalaaksonen** [UniversityOfHelsinkiCS/prkl#42]
Opettaja pystyy (omalta kurssiltaan) poistamaan ilmoittautumisen milloin vain, vaikka ryhmät olisivat jo luotu. Muistetaan hyväksyntä-ikkuna tms. Ilmoittautumisen voi poistaa lopullisesti tietokannasta.

- [x] frontiin nappuloita ja toiminnot
- [x] tietokantakysely
- [x] testaus
- [x] bug: poisto onnistuu vain kursseilta, joihin ei liity lainkaan kysymyksiä

**Comment by happoni** [comment]
Ilmoittautumisen poisto kurssilta, jossa on kysymyksiä, ei onnistu, sillä tietokannasta ei poisteta samalla liitostauluista fk:ta. Cascade-toiminnot lienevät pielessä.
